version: '3.8'

services:
  api:
    build: .
    command: python Back/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}


  db:
    image: postgres:latest
    volumes:
      - .:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"


